# Generated by Django 5.2.1 on 2025-05-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDepartments',
            fields=[
                ('departmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Department',
                'verbose_name_plural': 'Faculty Departments',
                'db_table': 'faculty_departments',
            },
        ),
        migrations.CreateModel(
            name='FacultyDesignations',
            fields=[
                ('designationId', models.IntegerField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Designation',
                'verbose_name_plural': 'Faculty Designations',
                'db_table': 'faculty_designations',
            },
        ),
        migrations.CreateModel(
            name='StudentsCourse',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Course',
                'verbose_name_plural': 'Student Courses',
                'db_table': 'students_courses',
            },
        ),
        migrations.CreateModel(
            name='StudentsStreams',
            fields=[
                ('streamId', models.IntegerField(primary_key=True, serialize=False)),
                ('streamName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Stream',
                'verbose_name_plural': 'Student Streams',
                'db_table': 'students_streams',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('userType', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='faculty', max_length=20)),
                ('institutionId', models.CharField(default='1234567890', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='StudentsCourseDivisions',
            fields=[
                ('divisionId', models.IntegerField(primary_key=True, serialize=False)),
                ('divisionName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_divisions', to='home.studentscourse')),
            ],
            options={
                'verbose_name': 'Course Division',
                'verbose_name_plural': 'Course Divisions',
                'db_table': 'course_divisions',
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.facultydepartments')),
                ('designationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.facultydesignations')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.users')),
            ],
            options={
                'verbose_name': 'Faculty Group',
                'verbose_name_plural': 'Faculty Groups',
                'db_table': 'faculty_groups',
            },
        ),
    ]
