# Generated by Django 5.2.1 on 2025-05-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDesignations',
            fields=[
                ('designationId', models.IntegerField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'db_table': 'designations',
            },
        ),
        migrations.RenameModel(
            old_name='Departmants',
            new_name='FacultyDepartmants',
        ),
    ]
