# Generated by Django 5.2.1 on 2025-05-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_facultydesignations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultydepartmants',
            options={'verbose_name': 'Faculty Department', 'verbose_name_plural': 'Faculty Departments'},
        ),
        migrations.AlterModelOptions(
            name='facultydesignations',
            options={'verbose_name': 'Faculty Designation', 'verbose_name_plural': 'Faculty Designations'},
        ),
        migrations.AlterModelTable(
            name='facultydepartmants',
            table='faculty_departments',
        ),
        migrations.AlterModelTable(
            name='facultydesignations',
            table='faculty_designations',
        ),
    ]
