# Generated by Django 5.2.1 on 2025-05-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_facultydepartmants_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacultyDepartmants',
            new_name='FacultyDepartments',
        ),
    ]
