# Generated by Django 5.2.1 on 2025-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_groups_users_is_staff_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
