# Generated by Django 5.2.1 on 2025-05-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_facultydepartmants_facultydepartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyusers',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
