# Generated by Django 5.2.1 on 2025-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydesignations',
            name='level',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='facultydesignations',
            name='designationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
