# Generated by Django 5.2.1 on 2025-05-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_facultyusers_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.facultydepartments')),
                ('designationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.facultydesignations')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_groups', to='home.facultyusers')),
            ],
            options={
                'verbose_name': 'Faculty Group',
                'verbose_name_plural': 'Faculty Groups',
                'db_table': 'faculty_groups',
            },
        ),
    ]
