# Generated by Django 5.2.1 on 2025-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_facultygroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyusers',
            name='username',
        ),
        migrations.AddField(
            model_name='facultyusers',
            name='facultyId',
            field=models.CharField(default='1234567890', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
